---
title: "Applied Methods in Statistics Final Project"
subtitle: "Hotel Booking Cancellation Prediction"
author: "Ching-Yeh Chen (ID: 313554049)"
date: "2025-06-04"
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 2
    number_sections: true
    css: style.css
bibliography: references.bib
csl: ieee.csl
url: https://github.com/cyc6221/Hotel-Booking-Cancellation-Prediction
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(ggplot2)
library(dplyr)
library(scales)
library(knitr)
```

<!-- chap 1 -->

# Problem Statement

```{r child="ProblemStatement.Rmd"}
```

<!-- chap 2 -->

# Dataset Description and Data Preprocessing

```{r child="Dataset.Rmd"}
```

<!-- chap 3 -->

# Exploratory Data Analysis

```{r child="Visualization.Rmd"}
```

<!-- chap 4 -->

# Analysis Process Designed for the Problem

```{r child="ProcessDesign.Rmd"}
```

<!-- chap 5 -->

# Analysis Results

```{r child="Result.Rmd"}
```

```{r child="Result2.Rmd"}
```

```{r child="Result3.Rmd"}
```

<!-- chap 6 -->

# Conclusion and Future Directions

```{r child="Conclusion.Rmd"}
```

<!-- chap 7 -->

# References

::: {#refs}
:::

---

# Appendix

## Project Repository  

Source code and materials:  
[https://github.com/cyc6221/Hotel-Booking-Cancellation-Prediction](https://github.com/cyc6221/Hotel-Booking-Cancellation-Prediction)
